### ISSUE TITLE
01_setup_abfe notebook crashes on try.openbiosim.org

### ISSUE THREAD

**Issue by akalpokas** [OpenBioSim/biosimspace_tutorials#11]
Running exercise 3 in tutorial https://github.com/OpenBioSim/biosimspace_tutorials/blob/main/04_fep/03_ABFE/01_setup_abfe.ipynb notebook on https://try.openbiosim.org i.e. the following code:

```python
traj = BSS.Trajectory.Trajectory(trajectory="output/restraint_search/gromacs.xtc",
                                 topology="input/complex/mif_mif180.prm7")
                                 
restraint = BSS.FreeEnergy.RestraintSearch.analyse("output/restraint_search", system, traj, 
                                                    298 * BSS.Units.Temperature.kelvin, method='BSS',
                                                    append_to_ligand_selection="name CAR CAL NAV NAM NAN")

#Check the indices of the anchor points as follows:

restraint.toString(engine="SOMD")
```

Seems to always crash the notebook kernel. Perhaps this is due to lack of resources available on the jupyter cloud instance?

**Comment by akalpokas** [comment]
Most cells in this tutorial notebook that involve restraint code crash the notebook kernel on https://try.openbiosim.org/

**Comment by chryswoods** [comment]
There's a hard memory limit of 2 GB of RAM per user of the notebook server. My guess is that the kernel is being killed because the restraint code is using more than that. I've just upped the limit to 4 GB per user. Could you try again and see if it still crashes?

**Comment by jmichel80** [comment]
But this used to work on this server. I’m not aware of updates to the restraint code that made it to 2023.3 . maybe @fjclark can comment ?

**Comment by akalpokas** [comment]
With increased RAM it seems to work better, exercises 3 and 4 now can be run, but exercise 5 still crashes. They also take around ~2-3 mins to execute, but I'll assume that won't be a problem for the workshop.

**Comment by chryswoods** [comment]
I could boost the memory a bit more. The current server is a D4v3, that is 4 cores and 16 GB memory.

https://learn.microsoft.com/en-us/azure/virtual-machines/dv3-dsv3-series

The planned server for the workshop will be a D64v3, which has 64 cores and 256GB. The memory limit is a cap, meaning that jobs above this will be killed. If you assume that attendees won't all be running the memory-intensive things at the same time then we Vicks go for a higher cap.

But - be aware that memory is the main limiting factor for number of attendees. The notebook server was set to 2 GB so that we could fit 6-7 concurrent users with memory spare for the infrastructure. Going to 4 GB means we can only safely got to 3 concurrent users. For the workshop server, 4 GB safely allows 64 concurrent users when we expect more to attend (hence they can't all run the restraints job at the same time as you'd run out of memory).

Aside from the memory change yesterday, I haven't changed the notebook server since the last time @jmichel80 asked for an update (I can't remember when that was).

**Comment by fjclark** [comment]
> But this used to work on this server. I’m not aware of updates to the restraint code that made it to 2023.3 . maybe @fjclark can comment ?

No, I don't remember updating the restraints code since the previous workshop.

**Comment by jmichel80** [comment]
Same issue with https://github.com/OpenBioSim/biosimspace_tutorials/blob/main/04_fep/03_ABFE/02_analysis_abfe.ipynb
